### PR TITLE
added incomplete workshop, and script to dl weights

### PR DESCRIPTION
**Pull request by brandons209**
the script allows downloading of weight file from google drive. much of the explaination needs to be added but the code itself is pretty straight forward.

### CODE REVIEW

**Comment by jmuchovej** [comment]
@brandons209 iirc, you said this was done, or we still waiting on `colab` kinks? 🤔

**Comment by brandons209** [comment]
Okay, finished workshop. needs to be reviewed.

**Review by jmuchovej — COMMENTED** [review]
i believe this should be good. i'll be checking in a sec, then approving.

**Review by jmuchovej — APPROVED** [review]
metadata fixed. lool.

**Pull request merged**
